### ISSUE TITLE
Not working in IE

### ISSUE THREAD

**Issue by Ciwan1859** [koldyr/BingKmlParser#1]
Thanks for this Dzianis. This works for me in all browsers except IE! Any ideas? It is failing on this line:

`BingKmlParser.prototype.parseStyles = function (kmlDom) {}`

**Comment by koldyr** [comment]
Hi
Thanks for feedback. What error do you get? What do you see in Browser JS console?

**Comment by koldyr** [comment]
just tested in IE11/Edge. works fine.
