### ISSUE TITLE
Parser not finding Styles in KML

### ISSUE THREAD

**Issue by tmiranda** [koldyr/BingKmlParser#2]
I am passing KML into the parser and it correctly identifies the geometries, but is not correctly identifying the colors for the different geometries. I tracked the problem I am seeing to the parseStyle method. The parseStyles method correctly finds each of 5 styles in my KML and passes each styleDom to the parseStyle method.  However the styleDom.find('PolyStyle') and styleDom.find('LineStyle') return an empty array.  So it is not ever parsing the colors for the styles.  Is this perhaps due to a change in the way the current version of jQuery handles xml fragments?

**Comment by koldyr** [comment]
thank you for finding this issue. i will take a look at it

**Comment by tmiranda** [comment]
Thanks!  Let me know if I can help with this.  I'll be glad to help work through or fix the issue.

**Comment by koldyr** [comment]
Ok, i checked my implementation with jquery-3.2.0.js. Works fine. Could you provide kml file you are working with?

**Comment by tmiranda** [comment]
Sure.  Here is an example of our kml data highlighting regions in the US:
<?xml version ="1.0" encoding = "UTF-8"?><kml xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2" xmlns:kml="http://www.opengis.net/kml/2.2" xmlns:atom="http://www.w3.org/2005/Atom"><Document><name>BoundaryType_rg</name><Style id="default"><LineStyle><color>ff000000</color></LineStyle><PolyStyle><color>9900aa00</color></PolyStyle></Style><Style id="westStyle"><LineStyle><color>32ffffff</color></LineStyle><PolyStyle><color>7F8EC441</color></PolyStyle></Style><Style id="mountainwestStyle"><LineStyle><color>32ffffff</color></LineStyle><PolyStyle><color>7F1B9DDE</color></PolyStyle></Style><Style id="midwestStyle"><LineStyle><color>32ffffff</color></LineStyle><PolyStyle><color>7FDC5B20</color></PolyStyle></Style><Style id="eastStyle"><LineStyle><color>32ffffff</color></LineStyle><PolyStyle><color>7F339933</color></PolyStyle></Style><Folder><name>MountainWest</name><open>1</open><Placemark><name>CO</name><styleUrl>#mountainwestStyle</styleUrl><Polygon><outerBoundaryIs><LinearRing><coordinates>-102.044456,37.641474,0.0 -102.042011,37.386279,0.0 -102.037208,36.988994,0.0 -102.997709,36.998524,0.0 -103.077866,36.99976,0.0 -103.993635,36.994469,0.0 -105.146173,36.993207,0.0 -105.213091,36.992604,0.0 -105.71346,36.99456,0.0 -105.992,36.99229,0.0 -106.472177,36.991504,0.0 -106.861249,36.989502,0.0 -106.89037,36.999084,0.0 -107.410821,36.997526,0.0 -107.47246,36.998777,0.0 -108.372473,36.999472,0.0 -109.04848,36.996641,0.0 -109.045602,37.630821,0.0 -109.043206,37.88742,0.0 -109.043464,38.152934,0.0 -109.055861,38.24492,0.0 -109.053948,38.494651,0.0 -109.051417,39.360966,0.0 -109.053529,39.51817,0.0 -109.052552,39.657382,0.0 -109.051263,40.210511,0.0 -109.046156,40.665291,0.0 -109.048315,40.998433,0.0 -107.918671,41.003375,0.0 -107.304051,41.000133,0.0 -106.865439,40.998457,0.0 -106.329126,41.001289,0.0 -106.203471,41.000085,0.0 -105.278798,40.996349,0.0 -104.934493,40.994289,0.0 -104.051706,41.003211,0.0 -103.572316,40.999648,0.0 -103.382957,41.000316,0.0 -102.652271,40.998124,0.0 -102.621257,41.000215,0.0 -102.047739,40.998071,0.0 -102.046992,40.74313,0.0 -102.046031,40.697319,0.0 -102.04762,40.431078,0.0 -102.047545,40.342644,0.0 -102.051536,39.998918,0.0 -102.049443,39.568693,0.0 -102.048802,39.562804,0.0 -102.047875,39.126753,0.0 -102.048973,39.037003,0.0 -102.047568,38.692551,0.0 -102.047584,38.615499,0.0 -102.04555,38.263344,0.0 -102.046061,38.253822,0.0 -102.043977,37.734399,0.0 -102.044456,37.641474,0.0</coordinates></LinearRing></outerBoundaryIs></Polygon></Placemark><Placemark><name>NM</name><styleUrl>#mountainwestStyle</styleUrl><Polygon><outerBoundaryIs><LinearRing><coordinates>-109.049495,32.442044,0.0 -109.051346,32.779551,0.0 -109.050526,33.205165,0.0 -109.050349,33.783302,0.0 -109.048653,34.591781,0.0 -109.046641,34.954646,0.0 -109.047846,35.996664,0.0 -109.04848,36.996641,0.0 -108.372473,36.999472,0.0 -107.47246,36.998777,0.0 -107.410821,36.997526,0.0 -106.89037,36.999084,0.0 -106.861249,36.989502,0.0 -106.472177,36.991504,0.0 -105.992,36.99229,0.0 -105.71346,36.99456,0.0 -105.213091,36.992604,0.0 -105.146173,36.993207,0.0 -103.993635,36.994469,0.0 -103.077866,36.99976,0.0 -102.997709,36.998524,0.0 -102.997401,36.49237,0.0 -103.027287,36.491592,0.0 -103.024048,36.056062,0.0 -103.022612,35.742327,0.0 -103.022294,35.623648,0.0 -103.026151,35.177266,0.0 -103.025251,34.96478,0.0 -103.022657,34.745333,0.0 -103.029646,34.30782,0.0 -103.033259,33.826182,0.0 -103.038736,33.565843,0.0 -103.043101,33.377831,0.0 -103.049331,32.953639,0.0 -103.060018,32.515545,0.0 -103.055641,32.085117,0.0 -103.058414,32.002023,0.0 -103.332549,32.004281,0.0 -103.729444,32.006229,0.0 -103.981377,32.006015,0.0 -104.019297,32.007404,0.0 -104.851068,32.003265,0.0 -104.922305,32.004382,0.0 -106.00324,32.001658,0.0 -106.378387,32.000747,0.0 -106.623626,32.001089,0.0 -106.650062,31.98033,0.0 -106.632605,31.97222,0.0 -106.633749,31.914101,0.0 -106.644079,31.895205,0.0 -106.616124,31.844741,0.0 -106.614987,31.817834,0.0 -106.539515,31.786305,0.0 -107.283567,31.785083,0.0 -108.203255,31.786903,0.0 -108.210648,31.343854,0.0 -109.045615,31.343453,0.0 -109.049495,32.442044,0.0</coordinates></LinearRing></outerBoundaryIs></Polygon></Placemark><Placemark><name>AZ</name><styleUrl>#mountainwestStyle</styleUrl><Polygon><outerBoundaryIs><LinearRing><coordinates>-114.520628,33.027707,0.0 -114.559089,33.036782,0.0 -114.609926,33.027002,0.0 -114.633967,33.033567,0.0 -114.64516,33.044412,0.0 -114.663952,33.038923,0.0 -114.711355,33.095383,0.0 -114.709463,33.122375,0.0 -114.67812,33.16725,0.0 -114.680051,33.224595,0.0 -114.687711,33.239258,0.0 -114.677693,33.268017,0.0 -114.735427,33.305708,0.0 -114.703604,33.352418,0.0 -114.724936,33.41106,0.0 -114.645092,33.419116,0.0 -114.630573,33.439425,0.0 -114.62109,33.468599,0.0 -114.598086,33.486127,0.0 -114.587062,33.509446,0.0 -114.529421,33.560073,0.0 -114.540247,33.580508,0.0 -114.527171,33.622137,0.0 -114.525264,33.665505,0.0 -114.536434,33.682735,0.0 -114.495676,33.708369,0.0…090195,35.254486,0.0 -90.106034,35.263935,0.0 -90.152216,35.264145,0.0 -90.16984,35.282654,0.0 -90.157084,35.306331,0.0 -90.106438,35.314772,0.0 -90.098793,35.345678,0.0 -90.105713,35.366067,0.0 -90.087227,35.381593,0.0 -90.075569,35.406613,0.0 -90.085251,35.418366,0.0 -90.112336,35.417775,0.0 -90.132562,35.407685,0.0 -90.14026,35.38313,0.0 -90.16791,35.38434,0.0 -90.17277,35.423802,0.0 -90.137368,35.442608,0.0 -90.102051,35.473651,0.0 -90.082321,35.478289,0.0 -90.074935,35.472426,0.0 -90.074027,35.42659,0.0 -90.060386,35.413494,0.0 -90.046873,35.417187,0.0 -89.999654,35.445537,0.0 -90.041906,35.512522,0.0 -90.040991,35.542928,0.0 -90.03314,35.552495,0.0 -89.989674,35.561757,0.0 -89.96236,35.532373,0.0 -89.947635,35.526983,0.0 -89.931262,35.529314,0.0 -89.921747,35.54614,0.0 -89.958118,35.578675,0.0 -89.957134,35.603184,0.0 -89.877526,35.633415,0.0 -89.863922,35.629825,0.0 -89.849281,35.645301,0.0 -89.85733,35.671141,0.0 -89.865265,35.673384,0.0 -89.893487,35.656051,0.0 -89.929827,35.676344,0.0 -89.952121,35.712564,0.0 -89.951122,35.734345,0.0 -89.909868,35.754914,0.0 -89.859955,35.748269,0.0 -89.827125,35.758348,0.0 -89.799986,35.7743,0.0 -89.790464,35.80563,0.0 -89.759877,35.817497,0.0 -89.736019,35.807114,0.0 -89.700908,35.827591,0.0 -89.701518,35.842113,0.0 -89.757794,35.871493,0.0 -89.766355,35.884177,0.0 -89.76299,35.896887,0.0 -89.738057,35.915087,0.0 -89.714763,35.911501,0.0 -89.664729,35.885722,0.0 -89.649416,35.894362,0.0 -89.645479,35.913874,0.0 -89.664271,35.937894,0.0 -89.713215,35.966397,0.0 -89.721836,35.999951,0.0 -89.688922,36.025867,0.0 -89.678249,36.083041,0.0 -89.667468,36.099386,0.0 -89.589502,36.129861,0.0 -89.589532,36.152089,0.0 -89.618639,36.183812,0.0 -89.676869,36.220935,0.0 -89.695737,36.240863,0.0 -89.694623,36.252204,0.0 -89.670666,36.254962,0.0 -89.618159,36.240966,0.0 -89.541725,36.257346,0.0 -89.535454,36.264605,0.0 -89.542313,36.280932,0.0 -89.606844,36.308103,0.0 -89.622874,36.334847,0.0 -89.605769,36.354817,0.0 -89.544632,36.345788,0.0 -89.519409,36.355996,0.0 -89.520081,36.401123,0.0 -89.545258,36.441023,0.0 -89.516098,36.471872,0.0 -89.533272,36.49817,0.0 -89.475898,36.498609,0.0 -89.492065,36.465525,0.0 -89.470908,36.446017,0.0 -89.448591,36.456442,0.0 -89.414785,36.502679,0.0 -89.346668,36.502611,0.0 -88.830373,36.499855,0.0 -88.826359,36.499908,0.0 -88.810719,36.499046,0.0 -88.512681,36.499547,0.0 -88.496026,36.498208,0.0 -88.042763,36.49657,0.0 -88.03508,36.5382,0.0 -88.041091,36.582721,0.0 -88.071341,36.679683,0.0 -87.870711,36.669423,0.0 -87.853537,36.641522,0.0 -87.693528,36.644489,0.0 -87.640655,36.645217,0.0 -87.346611,36.649277,0.0 -87.112703,36.651308,0.0 -87.068184,36.650811,0.0 -86.770535,36.652101,0.0 -86.510668,36.655074,0.0 -86.415444,36.650932,0.0 -86.198993,36.643291,0.0 -85.980611,36.633113,0.0 -85.785476,36.626685,0.0 -85.437375,36.618199,0.0 -85.300095,36.626101,0.0 -85.272498,36.625617,0.0 -84.998461,36.620983,0.0 -84.791057,36.605438,0.0 -84.781871,36.605076,0.0 -84.256777,36.595498,0.0 -84.254489,36.595453,0.0 -84.006747,36.592088,0.0 -83.9356,36.591291,0.0 -83.695609,36.584249,0.0 -83.675177,36.598704,0.0 -83.46421,36.59884,0.0 -83.275031,36.600467,0.0 -83.248388,36.589935,0.0 -83.210927,36.58809,0.0 -82.986697,36.59129,0.0 -82.849823,36.591041,0.0 -82.610839,36.591546,0.0 -82.296858,36.591801,0.0 -82.216661,36.594072,0.0 -82.154181,36.59515,0.0 -81.929303,36.595951,0.0 -81.918294,36.613609,0.0 -81.828898,36.611596,0.0 -81.652272,36.607674,0.0 -81.669835,36.589768,0.0 -81.702633,36.51946,0.0 -81.698115,36.4719,0.0 -81.740908,36.391908,0.0 -81.740213,36.361983,0.0 -81.70929,36.33385,0.0 -81.730325,36.329467,0.0 -81.83041,36.334779,0.0 -81.910994,36.290875,0.0 -81.932952,36.263444,0.0 -82.020295,36.129834,0.0 -82.077602,36.10026,0.0 -82.117926,36.096375,0.0 -82.153901,36.139738,0.0 -82.207585,36.147128,0.0 -82.26216,36.120488,0.0 -82.311784,36.122261,0.0 -82.373713,36.098807,0.0 -82.408283,36.075427,0.0 -82.475055,35.993284,0.0 -82.506794,35.97265,0.0 -82.554005,35.956216,0.0 -82.599165,35.963406,0.0 -82.605666,36.003654,0.0 -82.592094,36.022556,0.0 -82.604264,36.043094,0.0 -82.627909,36.054446,0.0 -82.643755,36.051829,0.0 -82.763095,35.99965,0.0 -82.773463,35.987607,0.0 -82.776308,35.956677,0.0 -82.808535,35.920975,0.0 -82.856137,35.947529,0.0 -82.895842,35.948463,0.0 -82.913939,35.92797,0.0 -82.906689,35.872317,0.0 -82.96262,35.791952,0.0 -82.986874,35.774091,0.0 -83.059829,35.782677,0.0 -83.118058,35.763908,0.0 -83.143533,35.762782,0.0 -83.185221,35.728983,0.0 -83.243725,35.718313,0.0 -83.253177,35.700804,0.0 -83.258999,35.691107,0.0 -83.298292,35.656423,0.0 -83.342903,35.653355,0.0 -83.386972,35.625313,0.0 -83.458173,35.597373,0.0 -83.505684,35.559645,0.0 -83.560923,35.555269,0.0 -83.613751,35.571831,0.0 -83.672766,35.565062,0.0 -83.775775,35.552693,0.0 -83.830098,35.519149,0.0 -83.881125,35.510672,0.0 -83.909913,35.476564,0.0 -83.954608,35.455544,0.0</coordinates></LinearRing></outerBoundaryIs></Polygon></Placemark></Folder></Document></kml>

**Comment by tmiranda** [comment]
This is a kml file showing regions in the US.
[regions.kml.txt](https://github.com/koldyr/BingKmlParser/files/850677/regions.kml.txt)

**Comment by tmiranda** [comment]
When I debug and step through the code, in the _parseStyle_ method, on line 278,  _polyStyle_ comes back as empty.  So the find method on the styleDom does not find the ParseStyle element.  However looking at the styleDom content, it is there.  Let me know what other information I can provide!

**Comment by koldyr** [comment]
i tested parser with your file and here is result. Looks fine for me 
![image](https://cloud.githubusercontent.com/assets/4440270/24071542/bd8432fc-0be5-11e7-8afd-19f66a742a11.png)

Any additional info? Operating system, browser used... ?

**Comment by tmiranda** [comment]
Let me get you a screenshot of what I see when I parse the file. What is
interesting about your screenshot is that is actually not the correct
regions that are highlighted. Mutations look correct, but the color is What
is not working. Everything parses fine except the styles. I have tested it
on all major browsers and on iOS and Android with same result. Let me send
you a screenshot when I can get back to the system. Thanks for the
continued help!

**Comment by koldyr** [comment]
Is this the color you are expecting? 

![image](https://cloud.githubusercontent.com/assets/4440270/24078889/00fa79d8-0c8b-11e7-829a-a4d36a5cab0a.png)

**Comment by tmiranda** [comment]
Ok, I took this screenshot from the application we are rewriting.  This is
the same kml file I sent.  These are the colors and regions I would
expect.  As a note, the new system shows the regions correctly, but they
are all a shade of green (not the right shade of green ;) ).
[image: Inline image 1]

**Comment by koldyr** [comment]
sorry, i don't see your screenshot

**Comment by tmiranda** [comment]
See if that shows up.

On Mon, Mar 20, 2017 at 11:44 AM, Dzianis Halitski <notifications@github.com

**Comment by tmiranda** [comment]
![regions](https://cloud.githubusercontent.com/assets/186654/24112128/83d20d4a-0d66-11e7-9f85-51a432c13eef.png)

**Comment by tmiranda** [comment]
This is what I am currently getting.  Note the regions are correct, but the color is wrong.
![regionsactual](https://cloud.githubusercontent.com/assets/186654/24112267/007bf5e0-0d67-11e7-8479-4e93de0518b7.PNG)

**Comment by tmiranda** [comment]
The slight variation you see in the greens in the screenshot is an anomaly and not actually a different color.

**Comment by koldyr** [comment]
yes, now it's visible.
still your regions.kml is not what we see on screenshots.
in kml what i've got i see 5 styles: 
default - color  9900aa00
westStyle - color 7F8EC441
mountainwestStyle - color 7F1B9DDE
midwestStyle - color 7FDC5B20
eastStyle - 7F339933

Here is resulting colors comes from parser

![image](https://cloud.githubusercontent.com/assets/4440270/24114321/d5c3d30a-0db0-11e7-90c8-33ad0e682e49.png)

i think they are correct. they corresponds to colors on your screenshots.

About Placemarks in  regions.kml - there only 3. so i assume regions.kml is not what you get in your program

**Comment by tmiranda** [comment]
I think we are on the same page now, but the problem I am seeing is that the styles are not parsed at all when I run the parser.  Back to my original message, styleDom.find('PolyStyle') and styleDom.find('LineStyle') return nothing.  It is as though the parser cannot find the PolyStyle element in the styleDom.  When I look at styleDom in the debugger, I see the PolyStyle element, but after the call to styleDom.find('PolyStyle'), there is nothing in the variable polyStyle.  Does that make sense?  It is as though "find" did not work.

**Comment by koldyr** [comment]
well, i still not sure what is going on in your case. But I loaded your kml file with my parser and shown to you colors which is in there. or you are using different kml which really parsed wrongly or you have some special version of jQuery. As soon as i reproduce your case i may fix it. up till now i don't see any problem on parser side

**Comment by koldyr** [comment]
better off, if you provide full kml file with all polygons and it's styles

**Comment by koldyr** [comment]
@tmiranda , any news from your side? Is everything fine? Can i close this issue?

**Comment by tmiranda** [comment]
Sorry for the delay.  Got pulled in a couple of other directions.  Since you are having trouble reproducing the problem, I am going to try to put together something to reproduce and then see if I can work on finding something that fixes the issue.  Then I can share that with  you and we'll have something more concrete to look at.  Thanks for your continued help!
